# Site settings
# Enter your own credentials here
title: "Noah Paulson Research Blog"
email: noahhpaulson@gmail.com
description: >
  Noah Paulson's personal research blog
baseurl: "/research-blog" # replace ``/research-pages`` with the name of the parents repository
url: "npaulson.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: Materials-Informatics-Lab
  repo: research-pages
  # Branch hosting Github pages
  branch: gh-pages
